import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'va-bg': '#F6F5F2',
        'va-surface': '#FFFFFF',
        'va-surface-alt': '#F0EFEB',
        'va-navy': '#1A1A2E',
        'va-navy-light': '#2E2E50',
        'va-gold': '#B8982A',
        'va-gold-light': '#D4B94E',
        'va-gold-subtle': '#F8F4E6',
        'va-forest': '#0F2920',
        'va-forest-light': '#1C4A3A',
        'va-emerald': '#2D8C64',
        'va-emerald-light': '#3AA878',
        'va-emerald-subtle': '#EDF7F2',
        'va-slate': '#1C1F2E',
        'va-slate-light': '#31364A',
        'va-amber': '#D4870E',
        'va-amber-light': '#E9A033',
        'va-amber-subtle': '#FDF6E9',
        'va-admin': '#18181B',
        'va-indigo': '#6366F1',
        'va-indigo-subtle': '#EEF2FF',
        'va-text': '#1A1A2E',
        'va-text-secondary': '#5C5C6F',
        'va-text-muted': '#8E8E9A',
        'va-border': '#E2E1DC',
        'va-border-light': '#EDECE8',
        'va-success': '#2D6A4F',
        'va-success-bg': '#EBF5F0',
        'va-success-border': '#C6E0D4',
        'va-warning': '#92710A',
        'va-warning-bg': '#FEF9EC',
        'va-warning-border': '#F0E2A8',
        'va-error': '#9B2C2C',
        'va-error-bg': '#FDF2F2',
        'va-error-border': '#F5C6C6',
        'va-info': '#2563EB',
        'va-info-bg': '#EFF6FF',
      },
      fontFamily: {
        heading: ['"DM Serif Display"', 'Georgia', 'serif'],
        body: ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        va: '4px',
        'va-sm': '3px',
        'va-md': '5px',
      },
    },
  },
  plugins: [],
};

export default config;
